# -*- coding: utf-8 -*-
"""streamlit_video_player.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqsslrFM5-8hBi-LZqWAs1VwS83Z1ea_
"""

# streamlit_video_player.py
import streamlit as st
import cv2
import base64
import time

def play_video_in_single_window(video_path, width=320, height=240, fps=25):
    """Plays video in Streamlit app."""
    try:
        # Create a placeholder for the video
        video_placeholder = st.empty()

        # Open video file
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise ValueError(f"Could not open video at {video_path}")

        frame_delay = 1 / fps

        while cap.isOpened():
            ret, frame = cap.read()
            if ret:
                # Resize frame
                frame = cv2.resize(frame, (width, height))

                # Convert frame to RGB (Streamlit expects RGB, cv2 uses BGR)
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                # Encode frame to base64
                _, frame_encoded = cv2.imencode('.jpg', frame_rgb)
                frame_bytes = frame_encoded.tobytes()
                frame_b64 = base64.b64encode(frame_bytes).decode('utf-8')

                # Display frame in Streamlit
                video_placeholder.image(
                    frame_rgb,
                    caption='Video Playback',
                    use_column_width=False,
                    width=width
                )

                time.sleep(frame_delay)
            else:
                break

        cap.release()
        st.success("Video playback completed!")

    except Exception as e:
        st.error(f"An error occurred: {e}")

def main():
    st.title("Simple Video Player")
    st.write("SED690 - SIT@KMUTT - Feb 2025")

    # File uploader
    uploaded_file = st.file_uploader("Choose a video file", type=['mp4', 'avi', 'mov'])

    # Video settings
    col1, col2, col3 = st.columns(3)
    with col1:
        width = st.slider("Width", 100, 800, 320)
    with col2:
        height = st.slider("Height", 100, 600, 240)
    with col3:
        fps = st.slider("FPS", 1, 60, 25)

    if uploaded_file is not None:
        # Save uploaded file temporarily
        with open("temp_video.mp4", "wb") as f:
            f.write(uploaded_file.getbuffer())

        if st.button("Play Video"):
            play_video_in_single_window("temp_video.mp4", width, height, fps)

if __name__ == "__main__":
    main()